# Site settings
title: Kylin Ya!
SEOTitle: KylinChen | Blog
header-img: img/tag-bg-o.jpg
email: k1017856853@icloud.com
description: "Sophomore CSer in Shanghai JioaTong University, as well a poet and musician."
keyword: "Kylin, KylinChen, 陈麒麟的博客, SJTU"
url: "http://KylinC.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/KylinC/KylinC.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Sophomore in Shanghai JioaTong University."
sidebar-avatar: /img/avatar_door.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     Ky的Lin呀
#zhihu_username:     
github_username:    KylinC
facebook_username:  Kylin Chen
#jianshu_username:   c9121038ec76
twitter_username:   KylinChan11




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
#disqus_username: kylinc

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: d87f2a6bf4cb07241869                          #生成的clientID
  clientSecret: 90a9070098496951321a72572417693ce6bb7540   #生成的clientSecret
  repo: KylinC.github.io    #仓库名称
  owner: KylinC    #github用户名
  admin: KylinC
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 7690a423f7829c09c567dc001ff14d0d

# Google Analytics
ga_track_id: 'UA-136749660-1'            # Format: UA-xxxxxx-xx
ga_domain: kylinchen.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "SJTU",
        href: "https://www.sjtu.edu.cn/"
    },{
        title: "Google",
        href: "https://www.google.com.hk/"
    },{
        title: "GitHub",
        href: "https://github.com/"
    }
]
